set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm-kitty:RGB"

set -g history-limit 65536

set -g prefix C-j

set -g mouse on
set -g mode-keys vi
set -g base-index 1
set -g renumber-windows on
set -g set-clipboard external

set -g status "on"
set -g status-keys vi

set -g status-style bg=colour0,fg=colour1
set -g message-style bg=colour0,fg=colour1
set -g message-command-style bg=colour0,fg=colour1
set-window-option -g mode-style bg=colour0,fg=colour1

setw -g aggressive-resize on
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind a run-shell "~/.tmux/scripts/layout.sh"
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi 'Escape' send -X clear-selection

set -sg escape-time 10
set -g focus-events on

run-shell ~/sources/tmux-resurrect/resurrect.tmux
# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
set -g @resurrect-strategy-nvim 'session'
